spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/order_db}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8084}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
