spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/order_db}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8084}
  tomcat:
    max-http-header-size: 1048576

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
