spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cart_db}

server:
  port: ${SERVER_PORT:8082}
  tomcat:
    max-http-header-size: 1048576

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
