spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cart_db}

server:
  port: ${SERVER_PORT:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
